### ISSUE TITLE
USER STORY 8: User can be anonymous

### ISSUE THREAD

**Issue by sarahliz24** [sarahliz24/AYA-Teen-Room#12]
As a **teen room user** I can **post anonymously** so that **I can be honest with my opinion without worrying people will know who I am**

# Acceptance Criteria
a. user can choose own username at sign up
b. only chosen username is displayed to user throughout app
c. medical id is included in profile for safeguarding but not displayed to anyone but site admin in admin panel

# Tasks
- [x] Registration function set up 
- [x] Registration allows user to choose username (must be unique)
- [x] User can log in with chosen username
