### ISSUE TITLE
USER STORY 1: Users must sign in to see/give feedback

### ISSUE THREAD

**Issue by sarahliz24** [sarahliz24/AYA-Teen-Room#14]
As a **teen room user** I can **be a registered site user** so that **I know only my teen room peers are on the site**

# Acceptance Criteria
a. Only logged in users can see feedback posts
b. User who is not logged in can only view home page or sign up
c.  Successful log in redirects user to feedback page

# Tasks
- [x] User can log in via a log in button
- [x] Log in authenticates user ((user in database, user is active)
- [x] User who is not logged in cannot view feedback page
