### ISSUE TITLE
USER STORY 5: User knows login status

### ISSUE THREAD

**Issue by sarahliz24** [sarahliz24/AYA-Teen-Room#29]
As a **teen room user** I can **receive messages about login status** so that **i know if I have logged in or out successfully**

# Acceptance Criteria
a. user name is displayed when user is logged in
b. message displayed when user logs out
c. user is returned to home page on log-out

# Tasks
- [x] set up user name display when logged in
- [x] set up messaging when user logs out
- [x] log out returns user to home page
