### ISSUE TITLE
USER STORY 16: Medical ID

### ISSUE THREAD

**Issue by sarahliz24** [sarahliz24/AYA-Teen-Room#30]
As a **room owner** I can **view medical id of users** so that **I can engage in safeguarding if there is an issue with a post of concern**

# Acceptance Criteria
a. User provides medical ID during registration
b. Site owner can view user medical id in admin panel
c. medical ID is not visible to other users

# Tasks
- [x] collect medical id from user at registration
- [x] configure admin panel to display medical id of users
- [x] only username is shown on feedback posts
- [x]  medical id user entry is validated to ensure correct length
