### ISSUE TITLE
USER STORY 2: User can edit profile

### ISSUE THREAD

**Issue by sarahliz24** [sarahliz24/AYA-Teen-Room#33]
As a **teen room user** I can **edit my details** so that **i have control over my username and other details**

# Acceptance Criteria
a. User can edit profile details (username, birthdate, medical id, first name)
b. Option to edit profile is obvious to user
c. Option to edit profile only available to logged in user
d. User is given successful message when edit performed

# Tasks
- [ ] Add profile function for user
- [ ] Allow user to edit profile
- [ ] Place profile edit link in logged in toolbar only
